name:  Get active branch name
description: Get active branch name for any type of the trigger (workflow_dispatch, pull_request, etc.)
outputs:
  branch-name:
    description: Branch name
    value: ${{ steps.extract-branch-name.outputs.branch-name }}
runs:
  using: composite
  steps:
    - name: Extract branch name
      id: extract-branch-name
      shell: bash
      run: echo "##[set-output name=branch-name;]$(echo ${GITHUB_REF#refs/heads/})"