name: Build image
inputs:
  ecr-repository:
    description: ECR repository
    required: true
  github-sha:
    description: GitHub SHA
    required: true
  github-ref:
    description: GitHub ref
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract branch name
      id: extract-branch-name
      uses: ./shared-github-actions/extract-branch-name
      with:
        github-ref: ${{ inputs.github-ref }}

    - name: Build image
      shell: bash
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        GITHUB_SHA: ${{ inputs.github-sha }}
        GITHUB_BRANCH_NAME: ${{ steps.extract-branch-name.outputs.branch-name }}
      run: |
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME || true
        docker build \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME \
          --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME \
          .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_BRANCH_NAME